eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: courses
          uri: http://localhost:8091
          predicates:
            - Path=/api/course/**
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**